local c = {
  bg = "#000000",
  surface = "#000a0d",
  elevated = "#001114",
  panel = "#001a1f",
  panel_highlight = "#00252b",
  fg = "#b8fbff",
  fg_soft = "#86eaf0",
  dim = "#2a5a60",
  dimmer = "#17383d",
  accent = "#00e5ff",
  accent_bright = "#7dffff",
  highlight = "#39ff88",
  highlight_dim = "#1a5c38",
  alert = "#ff4444",
}

if vim.g.colors_name then
  vim.cmd("highlight clear")
end

if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "tron"

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local function link(group, target)
  hi(group, { link = target })
end

vim.g.terminal_color_0 = c.bg
vim.g.terminal_color_1 = c.alert
vim.g.terminal_color_2 = c.highlight
vim.g.terminal_color_3 = c.highlight_dim
vim.g.terminal_color_4 = c.accent
vim.g.terminal_color_5 = c.dim
vim.g.terminal_color_6 = c.accent
vim.g.terminal_color_7 = c.fg
vim.g.terminal_color_8 = c.dimmer
vim.g.terminal_color_9 = "#ff7777"
vim.g.terminal_color_10 = "#77ffad"
vim.g.terminal_color_11 = c.highlight
vim.g.terminal_color_12 = c.accent_bright
vim.g.terminal_color_13 = c.fg_soft
vim.g.terminal_color_14 = c.accent_bright
vim.g.terminal_color_15 = "#ffffff"

hi("Normal", { fg = c.fg, bg = c.bg })
hi("NormalNC", { fg = c.fg_soft, bg = c.bg })
hi("NormalFloat", { fg = c.fg, bg = c.surface })
hi("FloatBorder", { fg = c.accent, bg = c.surface })
hi("FloatTitle", { fg = c.highlight, bg = c.surface })
hi("ColorColumn", { bg = c.surface })
hi("Conceal", { fg = c.dim })
hi("Cursor", { fg = c.bg, bg = c.accent_bright })
hi("lCursor", { fg = c.bg, bg = c.highlight })
hi("CursorIM", { fg = c.bg, bg = c.highlight })
hi("CursorColumn", { bg = c.elevated })
hi("CursorLine", { bg = c.elevated })
hi("CursorLineNr", { fg = c.highlight, bg = c.elevated, bold = true })
hi("LineNr", { fg = c.dim })
hi("LineNrAbove", { fg = c.dimmer })
hi("LineNrBelow", { fg = c.dimmer })
hi("Directory", { fg = c.accent_bright })
hi("EndOfBuffer", { fg = c.bg })
hi("ErrorMsg", { fg = c.alert, bold = true })
hi("FoldColumn", { fg = c.dim, bg = c.bg })
hi("Folded", { fg = c.dim, bg = c.surface })
hi("IncSearch", { fg = c.bg, bg = c.highlight, bold = true })
hi("CurSearch", { fg = c.bg, bg = c.highlight, bold = true })
hi("Search", { fg = c.accent_bright, bg = "#00343a" })
hi("Substitute", { fg = c.bg, bg = c.accent_bright, bold = true })
hi("MatchParen", { fg = c.highlight, bg = "#003522", bold = true })
hi("ModeMsg", { fg = c.highlight })
hi("MoreMsg", { fg = c.highlight })
hi("NonText", { fg = c.dimmer })
hi("Whitespace", { fg = c.dimmer })
hi("SpecialKey", { fg = c.dim })
hi("Question", { fg = c.highlight })
hi("QuickFixLine", { fg = c.highlight, bg = c.elevated, bold = true })
hi("SignColumn", { fg = c.dim, bg = c.bg })
hi("SpellBad", { sp = c.alert, undercurl = true })
hi("SpellCap", { sp = c.accent, undercurl = true })
hi("SpellLocal", { sp = c.highlight, undercurl = true })
hi("SpellRare", { sp = c.accent_bright, undercurl = true })
hi("StatusLine", { fg = c.accent, bg = c.surface })
hi("StatusLineNC", { fg = c.dim, bg = c.bg })
hi("TabLine", { fg = c.dim, bg = c.surface })
hi("TabLineFill", { fg = c.dim, bg = c.bg })
hi("TabLineSel", { fg = c.highlight, bg = c.elevated, bold = true })
hi("Title", { fg = c.accent_bright })
hi("Visual", { bg = "#00343a" })
hi("VisualNOS", { bg = "#00242a" })
hi("WarningMsg", { fg = c.accent_bright })
hi("WildMenu", { fg = c.bg, bg = c.accent })
hi("WinBar", { fg = c.accent, bg = c.bg })
hi("WinBarNC", { fg = c.dim, bg = c.bg })
hi("WinSeparator", { fg = c.accent, bg = c.bg })
hi("VertSplit", { fg = c.accent, bg = c.bg })

hi("Pmenu", { fg = c.fg, bg = c.surface })
hi("PmenuSel", { fg = c.accent_bright, bg = c.elevated, bold = true })
hi("PmenuKind", { fg = c.accent })
hi("PmenuKindSel", { fg = c.highlight, bg = c.elevated })
hi("PmenuExtra", { fg = c.dim })
hi("PmenuExtraSel", { fg = c.fg_soft, bg = c.elevated })
hi("PmenuSbar", { bg = c.panel })
hi("PmenuThumb", { bg = c.accent })

hi("Comment", { fg = c.dim, italic = true })
hi("Constant", { fg = c.accent_bright })
hi("String", { fg = c.highlight })
hi("Character", { fg = c.highlight })
hi("Number", { fg = c.accent_bright })
hi("Boolean", { fg = c.highlight })
hi("Float", { fg = c.accent_bright })
hi("Identifier", { fg = c.fg })
hi("Function", { fg = c.accent })
hi("Statement", { fg = c.accent })
hi("Conditional", { fg = c.accent })
hi("Repeat", { fg = c.accent })
hi("Label", { fg = c.accent_bright })
hi("Operator", { fg = c.accent_bright })
hi("Keyword", { fg = c.accent })
hi("Exception", { fg = c.alert })
hi("PreProc", { fg = c.fg_soft })
hi("Include", { fg = c.accent })
hi("Define", { fg = c.accent })
hi("Macro", { fg = c.accent })
hi("PreCondit", { fg = c.accent_bright })
hi("Type", { fg = c.accent_bright })
hi("StorageClass", { fg = c.accent })
hi("Structure", { fg = c.accent })
hi("Typedef", { fg = c.accent_bright })
hi("Special", { fg = c.accent_bright })
hi("SpecialChar", { fg = c.highlight })
hi("Tag", { fg = c.accent })
hi("Delimiter", { fg = c.dim })
hi("SpecialComment", { fg = c.dim, italic = true })
hi("Debug", { fg = c.alert })
hi("Underlined", { fg = c.accent_bright, underline = true })
hi("Ignore", { fg = c.dim })
hi("Error", { fg = c.alert })
hi("Todo", { fg = c.bg, bg = c.highlight, bold = true })

hi("DiagnosticError", { fg = c.alert })
hi("DiagnosticWarn", { fg = c.accent_bright })
hi("DiagnosticInfo", { fg = c.accent })
hi("DiagnosticHint", { fg = c.highlight })
hi("DiagnosticOk", { fg = c.highlight })
hi("DiagnosticVirtualTextError", { fg = c.alert, bg = "#190606" })
hi("DiagnosticVirtualTextWarn", { fg = c.accent_bright, bg = c.surface })
hi("DiagnosticVirtualTextInfo", { fg = c.accent, bg = c.surface })
hi("DiagnosticVirtualTextHint", { fg = c.highlight, bg = "#04170d" })
hi("DiagnosticVirtualTextOk", { fg = c.highlight, bg = "#04170d" })
hi("DiagnosticUnderlineError", { sp = c.alert, undercurl = true })
hi("DiagnosticUnderlineWarn", { sp = c.accent_bright, undercurl = true })
hi("DiagnosticUnderlineInfo", { sp = c.accent, undercurl = true })
hi("DiagnosticUnderlineHint", { sp = c.highlight, undercurl = true })
hi("DiagnosticUnderlineOk", { sp = c.highlight, undercurl = true })
hi("DiagnosticSignError", { fg = c.alert, bg = c.bg })
hi("DiagnosticSignWarn", { fg = c.accent_bright, bg = c.bg })
hi("DiagnosticSignInfo", { fg = c.accent, bg = c.bg })
hi("DiagnosticSignHint", { fg = c.highlight, bg = c.bg })
hi("DiagnosticSignOk", { fg = c.highlight, bg = c.bg })

hi("DiffAdd", { fg = c.highlight, bg = "#04170d" })
hi("DiffChange", { fg = c.accent, bg = c.surface })
hi("DiffDelete", { fg = c.alert, bg = "#190606" })
hi("DiffText", { fg = c.accent_bright, bg = c.panel_highlight, bold = true })
hi("Added", { fg = c.highlight })
hi("Changed", { fg = c.accent })
hi("Removed", { fg = c.alert })

hi("GitSignsAdd", { fg = c.highlight, bg = c.bg })
hi("GitSignsChange", { fg = c.accent, bg = c.bg })
hi("GitSignsDelete", { fg = c.alert, bg = c.bg })
hi("GitSignsAddNr", { fg = c.highlight, bg = c.bg })
hi("GitSignsChangeNr", { fg = c.accent, bg = c.bg })
hi("GitSignsDeleteNr", { fg = c.alert, bg = c.bg })

hi("LspReferenceText", { bg = c.panel })
hi("LspReferenceRead", { bg = c.panel })
hi("LspReferenceWrite", { bg = "#052315" })
hi("LspSignatureActiveParameter", { fg = c.highlight, bg = "#052315", bold = true })
hi("LspInlayHint", { fg = c.dim, bg = c.surface })
hi("CodeLens", { fg = c.dim })
hi("CodeLensSeparator", { fg = c.dimmer })

hi("@variable", { fg = c.fg })
hi("@variable.builtin", { fg = c.accent_bright })
hi("@variable.parameter", { fg = c.fg_soft })
hi("@variable.member", { fg = c.fg })
hi("@constant", { fg = c.accent_bright })
hi("@constant.builtin", { fg = c.highlight })
hi("@constant.macro", { fg = c.accent })
hi("@module", { fg = c.fg_soft })
hi("@label", { fg = c.accent_bright })
hi("@string", { fg = c.highlight })
hi("@string.documentation", { fg = c.fg_soft })
hi("@string.regexp", { fg = c.accent_bright })
hi("@string.escape", { fg = c.accent_bright })
hi("@string.special", { fg = c.accent_bright })
hi("@character", { fg = c.highlight })
hi("@character.special", { fg = c.accent_bright })
hi("@boolean", { fg = c.highlight })
hi("@number", { fg = c.accent_bright })
hi("@number.float", { fg = c.accent_bright })
hi("@type", { fg = c.accent_bright })
hi("@type.builtin", { fg = c.accent })
hi("@attribute", { fg = c.accent })
hi("@property", { fg = c.fg })
hi("@function", { fg = c.accent })
hi("@function.builtin", { fg = c.accent_bright })
hi("@function.call", { fg = c.accent })
hi("@function.macro", { fg = c.accent })
hi("@constructor", { fg = c.accent_bright })
hi("@operator", { fg = c.accent_bright })
hi("@keyword", { fg = c.accent })
hi("@keyword.coroutine", { fg = c.accent })
hi("@keyword.function", { fg = c.accent })
hi("@keyword.operator", { fg = c.accent_bright })
hi("@keyword.import", { fg = c.accent })
hi("@keyword.type", { fg = c.accent })
hi("@keyword.modifier", { fg = c.accent })
hi("@keyword.repeat", { fg = c.accent })
hi("@keyword.return", { fg = c.accent_bright })
hi("@keyword.debug", { fg = c.alert })
hi("@keyword.exception", { fg = c.alert })
hi("@keyword.conditional", { fg = c.accent })
hi("@keyword.directive", { fg = c.accent })
hi("@keyword.directive.define", { fg = c.accent })
hi("@punctuation.delimiter", { fg = c.dim })
hi("@punctuation.bracket", { fg = c.dim })
hi("@punctuation.special", { fg = c.accent })
hi("@comment", { fg = c.dim, italic = true })
hi("@comment.documentation", { fg = c.dim, italic = true })
hi("@comment.error", { fg = c.alert })
hi("@comment.warning", { fg = c.accent_bright })
hi("@comment.todo", { fg = c.bg, bg = c.highlight, bold = true })
hi("@comment.note", { fg = c.accent_bright })
hi("@markup.strong", { fg = c.fg, bold = true })
hi("@markup.italic", { fg = c.fg_soft, italic = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.underline", { underline = true })
hi("@markup.heading", { fg = c.accent_bright })
hi("@markup.quote", { fg = c.dim })
hi("@markup.math", { fg = c.highlight })
hi("@markup.link", { fg = c.accent, underline = true })
hi("@markup.link.label", { fg = c.accent_bright })
hi("@markup.link.url", { fg = c.dim, underline = true })
hi("@markup.raw", { fg = c.highlight })
hi("@markup.list", { fg = c.accent })
hi("@diff.plus", { fg = c.highlight })
hi("@diff.minus", { fg = c.alert })
hi("@diff.delta", { fg = c.accent })
hi("@tag", { fg = c.accent })
hi("@tag.attribute", { fg = c.fg_soft })
hi("@tag.delimiter", { fg = c.dim })

link("@lsp.type.namespace", "@module")
link("@lsp.type.type", "@type")
link("@lsp.type.class", "@type")
link("@lsp.type.enum", "@type")
link("@lsp.type.interface", "@type")
link("@lsp.type.struct", "@type")
link("@lsp.type.parameter", "@variable.parameter")
link("@lsp.type.variable", "@variable")
link("@lsp.type.property", "@property")
link("@lsp.type.enumMember", "@constant")
link("@lsp.type.function", "@function")
link("@lsp.type.method", "@function")
link("@lsp.type.macro", "@function.macro")
link("@lsp.type.decorator", "@attribute")

hi("CmpNormal", { fg = c.fg, bg = c.surface })
hi("CmpBorder", { fg = c.accent, bg = c.surface })
hi("CmpDocNormal", { fg = c.fg, bg = c.surface })
hi("CmpDocBorder", { fg = c.accent, bg = c.surface })
hi("CmpSel", { fg = c.accent_bright, bg = c.elevated, bold = true })
hi("CmpItemAbbr", { fg = c.fg })
hi("CmpItemAbbrDeprecated", { fg = c.dim, strikethrough = true })
hi("CmpItemAbbrMatch", { fg = c.accent_bright, bold = true })
hi("CmpItemAbbrMatchFuzzy", { fg = c.accent_bright, bold = true })
hi("CmpItemMenu", { fg = c.dim })
hi("CmpItemKind", { fg = c.accent })
hi("CmpItemKindText", { fg = c.fg_soft })
hi("CmpItemKindMethod", { fg = c.accent })
hi("CmpItemKindFunction", { fg = c.accent })
hi("CmpItemKindConstructor", { fg = c.accent_bright })
hi("CmpItemKindField", { fg = c.fg_soft })
hi("CmpItemKindVariable", { fg = c.fg_soft })
hi("CmpItemKindClass", { fg = c.accent_bright })
hi("CmpItemKindInterface", { fg = c.accent_bright })
hi("CmpItemKindModule", { fg = c.fg_soft })
hi("CmpItemKindProperty", { fg = c.fg_soft })
hi("CmpItemKindUnit", { fg = c.accent_bright })
hi("CmpItemKindValue", { fg = c.accent_bright })
hi("CmpItemKindEnum", { fg = c.accent_bright })
hi("CmpItemKindKeyword", { fg = c.accent })
hi("CmpItemKindSnippet", { fg = c.highlight })
hi("CmpItemKindColor", { fg = c.accent_bright })
hi("CmpItemKindFile", { fg = c.fg_soft })
hi("CmpItemKindReference", { fg = c.fg_soft })
hi("CmpItemKindFolder", { fg = c.accent_bright })
hi("CmpItemKindEnumMember", { fg = c.accent_bright })
hi("CmpItemKindConstant", { fg = c.accent_bright })
hi("CmpItemKindStruct", { fg = c.accent_bright })
hi("CmpItemKindEvent", { fg = c.highlight })
hi("CmpItemKindOperator", { fg = c.accent_bright })
hi("CmpItemKindTypeParameter", { fg = c.accent_bright })

hi("WhichKey", { fg = c.accent_bright })
hi("WhichKeyGroup", { fg = c.accent })
hi("WhichKeyDesc", { fg = c.fg })
hi("WhichKeySeparator", { fg = c.dim })
hi("WhichKeyFloat", { bg = c.surface })
hi("WhichKeyBorder", { fg = c.accent, bg = c.surface })
hi("WhichKeyValue", { fg = c.dim })

hi("BufferLineFill", { bg = c.bg })
hi("BufferLineBackground", { fg = c.dim, bg = c.surface })
hi("BufferLineBufferVisible", { fg = c.fg_soft, bg = c.surface })
hi("BufferLineBufferSelected", { fg = c.accent_bright, bg = c.bg, bold = true })
hi("BufferLineTab", { fg = c.dim, bg = c.surface })
hi("BufferLineTabSelected", { fg = c.highlight, bg = c.bg, bold = true })
hi("BufferLineTabClose", { fg = c.alert, bg = c.surface })
hi("BufferLineIndicatorSelected", { fg = c.highlight, bg = c.bg })
hi("BufferLineSeparator", { fg = c.bg, bg = c.surface })
hi("BufferLineSeparatorVisible", { fg = c.bg, bg = c.surface })
hi("BufferLineSeparatorSelected", { fg = c.accent, bg = c.bg })
hi("BufferLineModified", { fg = c.accent, bg = c.surface })
hi("BufferLineModifiedVisible", { fg = c.accent_bright, bg = c.surface })
hi("BufferLineModifiedSelected", { fg = c.highlight, bg = c.bg })
hi("BufferLineError", { fg = c.alert, bg = c.surface })
hi("BufferLineErrorSelected", { fg = c.alert, bg = c.bg, bold = true })
hi("BufferLineWarning", { fg = c.accent_bright, bg = c.surface })
hi("BufferLineWarningSelected", { fg = c.accent_bright, bg = c.bg, bold = true })
hi("BufferLineInfo", { fg = c.accent, bg = c.surface })
hi("BufferLineInfoSelected", { fg = c.accent, bg = c.bg, bold = true })
hi("BufferLineHint", { fg = c.highlight, bg = c.surface })
hi("BufferLineHintSelected", { fg = c.highlight, bg = c.bg, bold = true })

hi("TelescopeNormal", { fg = c.fg, bg = c.surface })
hi("TelescopeBorder", { fg = c.accent, bg = c.surface })
hi("TelescopePromptNormal", { fg = c.fg, bg = c.elevated })
hi("TelescopePromptBorder", { fg = c.highlight, bg = c.elevated })
hi("TelescopePromptTitle", { fg = c.bg, bg = c.highlight })
hi("TelescopePreviewTitle", { fg = c.bg, bg = c.accent })
hi("TelescopeResultsTitle", { fg = c.bg, bg = c.accent })
hi("TelescopeSelection", { fg = c.accent_bright, bg = c.elevated, bold = true })
hi("TelescopeMatching", { fg = c.highlight })

hi("SnacksNormal", { fg = c.fg, bg = c.surface })
hi("SnacksNormalNC", { fg = c.fg_soft, bg = c.surface })
hi("SnacksWinBar", { fg = c.accent, bg = c.surface })
hi("SnacksWinBarNC", { fg = c.dim, bg = c.surface })
hi("SnacksPicker", { fg = c.fg, bg = c.surface })
hi("SnacksPickerBorder", { fg = c.accent, bg = c.surface })
hi("SnacksPickerTitle", { fg = c.highlight, bg = c.surface })
hi("SnacksPickerMatch", { fg = c.highlight, bold = true })
hi("SnacksPickerPrompt", { fg = c.accent_bright })
hi("SnacksDashboardHeader", { fg = c.accent })
hi("SnacksDashboardDesc", { fg = c.fg })
hi("SnacksDashboardKey", { fg = c.highlight })
hi("SnacksDashboardIcon", { fg = c.accent_bright })
hi("SnacksDashboardSpecial", { fg = c.dim })
hi("SnacksNotifierInfo", { fg = c.accent, bg = c.surface })
hi("SnacksNotifierWarn", { fg = c.accent_bright, bg = c.surface })
hi("SnacksNotifierError", { fg = c.alert, bg = c.surface })
hi("SnacksNotifierDebug", { fg = c.dim, bg = c.surface })
hi("SnacksNotifierTrace", { fg = c.dim, bg = c.surface })

hi("NoiceCmdlinePopup", { fg = c.fg, bg = c.surface })
hi("NoiceCmdlinePopupBorder", { fg = c.accent, bg = c.surface })
hi("NoiceCmdlinePopupBorderSearch", { fg = c.highlight, bg = c.surface })
hi("NoiceCmdlineIcon", { fg = c.accent_bright })
hi("NoiceCmdlineIconSearch", { fg = c.highlight })
hi("NoicePopup", { fg = c.fg, bg = c.surface })
hi("NoicePopupBorder", { fg = c.accent, bg = c.surface })
hi("NoiceMini", { fg = c.fg, bg = c.surface })
hi("NoiceFormatProgressDone", { fg = c.highlight, bg = c.surface })
hi("NoiceFormatProgressTodo", { fg = c.dim, bg = c.surface })

hi("TroubleNormal", { fg = c.fg, bg = c.bg })
hi("TroubleNormalNC", { fg = c.fg_soft, bg = c.bg })
hi("TroubleText", { fg = c.fg })
hi("TroubleCount", { fg = c.highlight, bg = c.surface })
hi("TroubleIndent", { fg = c.dim })
hi("TroubleSignError", { fg = c.alert })
hi("TroubleSignWarning", { fg = c.accent_bright })
hi("TroubleSignInformation", { fg = c.accent })
hi("TroubleSignHint", { fg = c.highlight })

hi("FidgetTitle", { fg = c.accent })
hi("FidgetTask", { fg = c.dim })
hi("NotifyERRORBorder", { fg = c.alert })
hi("NotifyWARNBorder", { fg = c.accent_bright })
hi("NotifyINFOBorder", { fg = c.accent })
hi("NotifyDEBUGBorder", { fg = c.dim })
hi("NotifyTRACEBorder", { fg = c.dim })
hi("NotifyERRORIcon", { fg = c.alert })
hi("NotifyWARNIcon", { fg = c.accent_bright })
hi("NotifyINFOIcon", { fg = c.accent })
hi("NotifyDEBUGIcon", { fg = c.dim })
hi("NotifyTRACEIcon", { fg = c.dim })
hi("NotifyERRORTitle", { fg = c.alert })
hi("NotifyWARNTitle", { fg = c.accent_bright })
hi("NotifyINFOTitle", { fg = c.accent })
hi("NotifyDEBUGTitle", { fg = c.dim })
hi("NotifyTRACETitle", { fg = c.dim })

hi("RenderMarkdownH1", { fg = c.accent_bright })
hi("RenderMarkdownH2", { fg = c.accent })
hi("RenderMarkdownH3", { fg = c.highlight })
hi("RenderMarkdownH4", { fg = c.fg_soft })
hi("RenderMarkdownCode", { fg = c.fg, bg = c.elevated })
hi("RenderMarkdownCodeInline", { fg = c.highlight, bg = c.surface })
hi("RenderMarkdownDash", { fg = c.accent })
hi("RenderMarkdownBullet", { fg = c.accent })
hi("RenderMarkdownQuote", { fg = c.dim })
hi("RenderMarkdownLink", { fg = c.accent, underline = true })
hi("RenderMarkdownSuccess", { fg = c.highlight })
hi("RenderMarkdownInfo", { fg = c.accent })
hi("RenderMarkdownWarn", { fg = c.accent_bright })
hi("RenderMarkdownError", { fg = c.alert })

hi("LazyNormal", { fg = c.fg, bg = c.surface })
hi("LazyBorder", { fg = c.accent, bg = c.surface })
hi("LazyButton", { fg = c.accent, bg = c.surface })
hi("LazyButtonActive", { fg = c.highlight, bg = c.elevated, bold = true })
hi("LazyH1", { fg = c.bg, bg = c.accent })
hi("LazyH2", { fg = c.accent_bright })
hi("MasonNormal", { fg = c.fg, bg = c.surface })
hi("MasonHeader", { fg = c.bg, bg = c.accent })
hi("MasonHeaderSecondary", { fg = c.bg, bg = c.highlight })
hi("MasonHighlight", { fg = c.accent })
hi("MasonHighlightBlock", { fg = c.bg, bg = c.accent })
hi("MasonHighlightBlockBold", { fg = c.bg, bg = c.highlight, bold = true })
hi("MasonMuted", { fg = c.dim })
hi("MasonMutedBlock", { fg = c.dim, bg = c.surface })
